# Generated by Django 3.1.7 on 2021-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('UnitWeight', models.FloatField()),
                ('Picture', models.CharField(max_length=300)),
            ],
        ),
    ]
