# Generated by Django 3.1.7 on 2021-04-24 11:10

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('AdministratorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('IsApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('DateRegistered', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OrderDateTime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Address', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=50)),
                ('UnitWeight', models.FloatField()),
                ('Picture', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('ShipperID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=15)),
                ('DateRegistered', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('ContactTitle', models.CharField(max_length=40)),
                ('CompanyName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('WishID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Psm',
            fields=[
                ('PsmID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UnitPrice', models.FloatField()),
                ('UnitsOnOrder', models.IntegerField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ShippingStatus', models.CharField(max_length=40)),
                ('IsCOD', models.BooleanField(default=False, editable=False)),
                ('ItemQuantity', models.IntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('PsmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.psm')),
                ('ShipperID', models.ForeignKey(default=api.models.Shipper.get_random_shipper, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPending',
            fields=[
                ('ProductID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.product')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
