# Generated by Django 3.1.7 on 2021-04-14 17:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210406_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('DateRegistered', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
            ],
        ),
    ]
