# Generated by Django 3.1.7 on 2021-04-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='Password',
        ),
    ]
