# Generated by Django 3.1.7 on 2021-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210414_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
