# Generated by Django 3.1.7 on 2021-04-20 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('ShipperID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
    ]
