# Generated by Django 3.1.7 on 2021-04-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='ShipperID',
            new_name='SupplierID',
        ),
    ]
