# Generated by Django 3.1.7 on 2021-04-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210420_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Shipper',
        ),
        migrations.RenameField(
            model_name='shipper',
            old_name='SupplierID',
            new_name='ShipperID',
        ),
    ]
