# Generated by Django 3.1.7 on 2021-04-21 05:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210421_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=15)),
                ('DateRegistered', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('ContactTitle', models.CharField(max_length=40)),
                ('CompanyName', models.CharField(max_length=60)),
            ],
        ),
    ]
